### ISSUE TITLE
Enable local forwarder

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-LocalForwarder#17]
See how to do it here:

https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/0a98695091150dfa7a7dde806cc642f06b057862/src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptionsSetup.cs#L158-L162

**Comment by tokaplan** [comment]
Done, PR #20
